// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy9nJEcsfiE2QrrmuvTRN2oHX3jDeSHAc',
    appId: '1:476665932367:web:c29a0f5de72c2e10f9983a',
    messagingSenderId: '476665932367',
    projectId: 'tictactoe-e2925',
    authDomain: 'tictactoe-e2925.firebaseapp.com',
    storageBucket: 'tictactoe-e2925.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzda52zU0cu6PguVkF3ACjuBqC3dVH3tE',
    appId: '1:476665932367:android:c6b8e5b4b91d8e6cf9983a',
    messagingSenderId: '476665932367',
    projectId: 'tictactoe-e2925',
    storageBucket: 'tictactoe-e2925.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtoYMacaM-35tpWCW1W9tzvrches4q1pg',
    appId: '1:476665932367:ios:e95dd2a078b9585ef9983a',
    messagingSenderId: '476665932367',
    projectId: 'tictactoe-e2925',
    storageBucket: 'tictactoe-e2925.appspot.com',
    iosBundleId: 'com.example.tictactoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtoYMacaM-35tpWCW1W9tzvrches4q1pg',
    appId: '1:476665932367:ios:d9cac94d57fa7d2df9983a',
    messagingSenderId: '476665932367',
    projectId: 'tictactoe-e2925',
    storageBucket: 'tictactoe-e2925.appspot.com',
    iosBundleId: 'com.example.tictactoe.RunnerTests',
  );
}
